# Generated by Django 6.0.4 on 2026-04-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pairs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="📋", max_length=10)),
                ("ist_optional", models.BooleanField(default=False)),
                ("reihenfolge", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["reihenfolge"],
            },
        ),
        migrations.CreateModel(
            name="Aufgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=200)),
                ("ist_standard", models.BooleanField(default=True)),
                ("reihenfolge", models.PositiveSmallIntegerField(default=0)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paar_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eigene_aufgaben",
                        to="pairs.paarsession",
                    ),
                ),
                (
                    "kategorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aufgaben",
                        to="catalog.kategorie",
                    ),
                ),
            ],
            options={
                "ordering": ["reihenfolge", "id"],
            },
        ),
    ]
