# Generated by Django 6.0.4 on 2026-04-29 14:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaarSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("invite_expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("test_laeuft", "Test läuft"),
                            ("beide_fertig", "Beide fertig"),
                            ("plan_aktiv", "Plan aktiv"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                ("setup_kinder", models.BooleanField(default=False)),
                ("setup_haustiere", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_als_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_als_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
