# Generated by Django 6.0.4 on 2026-04-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pairs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Umverteilung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "management_neu",
                    models.CharField(
                        choices=[
                            ("person_a", "Partner:in A"),
                            ("person_b", "Partner:in B"),
                            ("beide", "Wir beide"),
                            ("extern", "Jemand anderes"),
                            ("abschaffen", "Aufgabe abschaffen"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ausfuehrung_neu",
                    models.CharField(
                        choices=[
                            ("person_a", "Partner:in A"),
                            ("person_b", "Partner:in B"),
                            ("beide", "Wir beide"),
                            ("extern", "Jemand anderes"),
                            ("abschaffen", "Aufgabe abschaffen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signoff_a", models.BooleanField(default=False)),
                ("signoff_a_at", models.DateTimeField(blank=True, null=True)),
                ("signoff_b", models.BooleanField(default=False)),
                ("signoff_b_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aufgabe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umverteilungen",
                        to="catalog.aufgabe",
                    ),
                ),
                (
                    "paar_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umverteilungen",
                        to="pairs.paarsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("paar_session", "aufgabe")},
            },
        ),
    ]
