# Generated by Django 6.0.4 on 2026-04-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pairs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("woche", models.DateField(help_text="Montag der jeweiligen Woche")),
                ("abgeschlossen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paar_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="pairs.paarsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-woche"],
                "unique_together": {("paar_session", "woche", "user")},
            },
        ),
        migrations.CreateModel(
            name="CheckInAntwort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ja", "Ja, hat funktioniert"),
                            ("teilweise", "Teilweise"),
                            ("nein", "Nein / nicht passiert"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notiz", models.TextField(blank=True)),
                (
                    "aufgabe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_antworten",
                        to="catalog.aufgabe",
                    ),
                ),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antworten",
                        to="checkins.checkin",
                    ),
                ),
            ],
            options={
                "unique_together": {("checkin", "aufgabe")},
            },
        ),
    ]
