# Generated by Django 6.0.4 on 2026-04-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("pairs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Antwort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "management",
                    models.CharField(
                        choices=[
                            ("ich", "Ich"),
                            ("partner", "Mein:e Partner:in"),
                            ("beide", "Wir beide"),
                            ("extern", "Jemand anderes"),
                            ("nicht_zutreffend", "Trifft nicht zu"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ausfuehrung",
                    models.CharField(
                        choices=[
                            ("ich", "Ich"),
                            ("partner", "Mein:e Partner:in"),
                            ("beide", "Wir beide"),
                            ("extern", "Jemand anderes"),
                            ("nicht_zutreffend", "Trifft nicht zu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("beantwortet_at", models.DateTimeField(auto_now=True)),
                (
                    "aufgabe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antworten",
                        to="catalog.aufgabe",
                    ),
                ),
                (
                    "paar_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antworten",
                        to="pairs.paarsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antworten",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("paar_session", "user", "aufgabe")},
            },
        ),
        migrations.CreateModel(
            name="TestAbschluss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abgeschlossen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paar_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abschluesse",
                        to="pairs.paarsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_abschluesse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("paar_session", "user")},
            },
        ),
    ]
